find_path(Bosslib_INCLUDE_DIRS bosslib/*.h)
find_library(Bosslib_LIBRARIES bosslib)

if (Bosslib_LIBRARIES AND Bosslib_INCLUDE_DIRS)
    set(Bosslib_FOUND YES)
    if (NOT Bosslib_FIND_QUIETLY)
        message(STATUS "Found bosslib: ${Bosslib_LIBRARIES}")
    endif ()
else ()
    if (Bosslib_FIND_REQUIRED)
        message(SEND_ERROR "Could NOT find bosslib")
    else ()
        if (NOT Bosslib_FIND_QUIETLY)
            message(STATUS "Could NOT find bosslib")
        endif ()
    endif ()
endif ()